baseURL: "http://bowang.finance" 
title: Bo Wang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: AboutMe
          url: aboutme/
          weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Advising
          url: advising/
          weight: 4 
        - name: Resources
          url: resources/
          weight: 6
        - name: Exam
          url: exam/
          weight: 6

params:
    description: "I am an Assistant Professor in Department of Accounting and Finance at Kean University. My research focuses on empirical corporate finance."
    author: Bo Wang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["aboutme","papers","courses","advising","resources", "exam"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Professor Bo Wang
          subtitle: "I am an Assistant Professor in Department of Accounting and Finance at Kean University. My research focuses on empirical corporate finance."
          imageUrl: "Bo Wang Headshot.jpg"
          imageWidth: 160
          imageHeight: 238
          buttons:
            - name: AboutMe
              url: aboutme/
            - name: Papers
              url: papers/
            - name: Courses
              url: courses/
            - name: Advising
              url: advising/
            - name: Resources
              url: resources/
            - name: Exam
              url: exam/

    socialIcons:
        - name: Google Scholar
          url: https://scholar.google.com/citations?view_op=list_works&hl=en&user=fw_ndEQAAAAJ
        - name: Research Gate
          url: https://www.google.com/url?q=https%3A%2F%2Fwww.researchgate.net%2Fprofile%2FBo-Wang-140&sa=D&sntz=1&usg=AOvVaw1ZNGhv4HwaIgQkm27dl3h3
        - name: LinkedIn
          url: https://www.google.com/url?q=https%3A%2F%2Fwww.linkedin.com%2Fin%2Fbo-wang-1762aa31%2F&sa=D&sntz=1&usg=AOvVaw3cGSjrEvUXOdp7ahvkdpVS
        - name: University Website
          url: https://www.kean.edu/directory/bo-wang

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Bo Wang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2